import { Controller, Post, UsePipes, ValidationPipe, Body } from '@nestjs/common';
import { ChatDto } from './dto/chat.dto';
import { SanitizePipe } from './pipes/sanitize.pipe';

@Controller('chat')
export class ChatController {
    @Post()
    @UsePipes(new ValidationPipe({ whitelist: true, forbidNonWhitelisted: true }), SanitizePipe)
    handleChat(@Body() payload: ChatDto) {
        
        console.log({payload});

        return {
            response: 'Here is the answer with personality.',
            source_agent_response: 'Text generated by the specialized agent.',
            agent_workflow: [
                { agent: 'RouterAgent', decision: 'KnowledgeAgent' },
                { agent: 'KnowledgeAgent' }
            ]
        };
    }
}
