services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: 
      context: ../../backend
      dockerfile: ../infrastructure/docker/backend/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../../backend/config/env/.env.production  # Production env file
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000
      - REDIS_TTL=900
      - LOG_LEVEL=info
    depends_on:
      - redis
volumes:
  redis_data: