services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: 
      context: ../../backend
      dockerfile: ../infrastructure/docker/backend/Dockerfile.dev
    ports:
      - "3003:3003"
    env_file:
      - ../../backend/config/env/.env
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3003
      - REDIS_TTL=900
      - LOG_LEVEL=info
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ../../backend/src:/app/src:ro
      - ../../backend/package.json:/app/package.json:ro
      - ../../backend/tsconfig.json:/app/tsconfig.json:ro
      - ../../backend/nest-cli.json:/app/nest-cli.json:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

volumes:
  redis_data:
